api:
  build: ./flipendo-api/
  command: npm start
  ports:
    - "3000:3000"
  environment:
    - VIRTUAL_HOST=api.flipendo.local
    - VIRTUAL_PORT=3000
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  links:
    - rabbitmq
website:
  build: ./flipendo-website/
  ports:
    - "9000:3000"
  environment:
    - VIRTUAL_HOST=website.flipendo.local
    - VIRTUAL_PORT=8080
  links:
    - api
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
    - "15672"
worker:
  build: ./flipendo-worker/
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  links:
    - rabbitmq
