api:
  build: ./flipendo-api/
  ports:
    - "3000:3000"
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  volumes:
    - ~/.aws:~/.aws:ro
  links:
    - rabbitmq
website:
  build: ./flipendo-website/
  ports:
    - "9000:3000"
  links:
    - api
rabbitmq:
  image: rabbitmq
  expose:
    - "5672"
    - "15672"
  environment:
    - RABBITMQ_NODENAME=flipendo-rabbit
worker:
  build: ./flipendo-worker/
  environment:
    - AWS_ACCESS_KEY_ID
    - AWS_SECRET_ACCESS_KEY
  volumes:
    - ~/.aws:~/.aws:ro
  links:
    - rabbitmq
